#spring:
#  thymeleaf:
#    cache: false
#  datasource:
#    name: dataSource
#    url: jdbc:log4jdbc:ArteryBase://172.25.16.68:5432/JXGLPT_NEW?currentSchema=db_akgl
#    username: jxglpt
#    password: jxglpt
    #type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy



#访问端口
server:
   port: 80
